//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// Created via this command line: "C:\Users\cciftci\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /url:"https://dsk365merge.veripark.com:444/dsk365merge" /namespace:"Xrm" /out:"C:\Users\cciftci\Desktop\Xrm\OptionSets.cs" /codecustomization:"DLaB.CrmSvcUtilExtensions.OptionSet.CreateOptionSetEnums,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.OptionSet.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:".\cciftci" /password:"*******" /domain:"." 
//------------------------------------------------------------------------------

namespace Cvc.Crm.Operation
{
    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
    public enum AsyncOperation_OperationType
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ActivityPropagation = 6,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALMAnomalyDetectionOperation = 73,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuditPartitionCreation = 41,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        BulkDelete = 13,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        BulkDeleteSubprocess = 23,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        BulkDuplicateDetection = 8,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        BulkEmail = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        CalculateOrganizationMaximumStorageSize = 22,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        CalculateOrganizationStorageSize = 18,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        CalculateRollupField = 57,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        CheckForLanguagePackUpdates = 42,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cleanupinactiveworkflowassemblies = 32,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        CleanupSolutionComponents = 71,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        CollectionOrganizationSizeStatistics = 20,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        CollectOrganizationDatabaseStatistics = 19,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        CollectOrganizationStatistics = 16,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConvertDateAndTimeBehavior = 62,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Databaselogbackup = 26,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseTuning = 21,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DBCCSHRINKDATABASEmaintenancejob = 28,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DBCCSHRINKFILEmaintenancejob = 29,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeletionService = 14,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateDetectionRulePublish = 7,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        EncryptionHealthCheck = 53,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        EntityKeyIndexCreation = 63,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExecuteAsyncRequest = 54,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        GoalRollUp = 40,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Import = 5,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ImportFileParse = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ImportSampleData = 38,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ImportSubprocess = 17,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ImportTranslation = 59,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        IncomingEmailProcessing = 51,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        IndexManagement = 15,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        MailboxTestAccess = 52,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        MassCalculateRollupField = 58,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchcodeUpdate = 12,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganizationFullTextCatalogIndex = 25,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        OutgoingActivity = 50,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        PosttoYammer = 49,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProvisionLanguagePack = 43,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        QuickCampaign = 11,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        RecurringSeriesExpansion = 35,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegenerateEntityRowCountSnapshotData = 46,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegenerateReadShareSnapshotData = 47,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reindexallindicesmaintenancejob = 30,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        RelationshipAssistantCards = 69,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResourceBookingSync = 68,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        SQMDataCollection = 9,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        StorageLimitNotification = 31,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemEvent = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        TransformParseData = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        UpdateContractStates = 27,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        UpdateEntitlementStates = 56,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        UpdateKnowledgeArticleStates = 65,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        UpdateOrganizationDatabase = 44,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        UpdateSolution = 45,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        UpdateStatisticIntervals = 24,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Workflow = 10,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
    public enum AsyncOperation_StatusCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Canceled = 32,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Canceling = 22,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 31,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        InProgress = 20,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pausing = 21,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Succeeded = 30,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Waiting = 10,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        WaitingForResources = 0,
    }
    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]

    public enum Solution_SolutionType
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Internal = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Snapshot = 1,
    }
}
